---
version: '2'
services:
  web:
    image: node:19.4.0-slim
    container_name: web
    user: "node"
    working_dir: /home/node/app
    networks:
      - webdev
    environment:
      - NODE_ENV=${NODE_ENV}
      - WDS_SOCKET_PORT=${WDS_SOCKET_PORT}
    volumes:
      - ./:/home/node/app
    restart: "no"
    command: "npm start"

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - webdev
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./nginx/sites-enabled/:/etc/nginx/sites-enabled/:ro
      - ./nginx/ssl/certs:/etc/ssl/certs:ro
      - ./nginx/ssl/private:/etc/ssl/private:ro
    depends_on:
      - web
    restart: "no"
    ports:
      - "80:80"
      - "443:443"

networks:
  webdev:
    driver: bridge
