---
name: "GitHub Pages"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  NODE_ENV: ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: "Run npm install, build, test"
        run: |
          npm ci
          npm run build --if-present
      - name: "Archive Build"
        uses: actions/upload-artifact@v3
        with:
          name: "copy-build-to-docs"
          path: build

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Download artifacts from build job"
        uses: actions/download-artifact@v3
        with:
          name: "copy-build-to-docs"
      - shell: bash
        run: |
          rm -rf docs && cp -aR build docs
          echo 'resume.jamesgrow.dev' >> docs/CNAME
